const avatarOptions = {
  isCircleOptions: [
    { value: true, text: "Circle" },
    { value: false, text: "Transparent" },
  ],
  circleColorOptions: [
    { value: "#6fb8e0", text: "Default" },
    { value: "#C0392B", text: "Red" },
    { value: "#D35400", text: "Orange" },
    { value: "#F1C40F", text: "Yellow" },
    { value: "#27AE60", text: "Green" },
    { value: "#3498DB", text: "Blue" },
    { value: "#8E44AD", text: "Purple" },
    { value: "#000000", text: "Black" },
    { value: "#FFFFFF", text: "White" },
  ],
  accessoriesTypeOptions: [
    { value: "Blank", text: "None" },
    { value: "Kurt", text: "Kurt Cobain Style" },
    { value: "Prescription01", text: "Glasses 1" },
    { value: "Prescription02", text: "Glasses 2" },
    { value: "Round", text: "Round" },
    { value: "Sunglasses", text: "Sunglasses" },
    { value: "Wayfarers", text: "Wayfarers" },
  ],
  clotheTypeOptions: [
    { value: "BlazerShirt", text: "Blazer Shirt" },
    { value: "BlazerSweater", text: "Blazer Sweater" },
    { value: "CollarSweater", text: "Collar Sweater" },
    { value: "GraphicShirt", text: "Graphic Shirt" },
    { value: "Hoodie", text: "Hoodie" },
    { value: "Overall", text: "Overall" },
    { value: "ShirtCrewNeck", text: "Shirt Crew Neck" },
    { value: "ShirtScoopNeck", text: "Shirt Scoop Neck" },
    { value: "ShirtVNeck", text: "Shirt VNeck" },
  ],
  clotheColorOptions: [
    { value: "Black", text: "Black" },
    { value: "Blue01", text: "Blue01" },
    { value: "Blue02", text: "Blue02" },
    { value: "Blue03", text: "Blue03" },
    { value: "Gray01", text: "Gray01" },
    { value: "Gray02", text: "Gray02" },
    { value: "Heather", text: "Heather" },
    { value: "PastelBlue", text: "Pastel Blue" },
    { value: "PastelGreen", text: "Pastel Green" },
    { value: "PastelOrange", text: "Pastel Orange" },
    { value: "PastelRed", text: "Pastel Red" },
    { value: "PastelYellow", text: "Pastel Yellow" },
    { value: "Pink", text: "Pink" },
    { value: "Red", text: "Red" },
    { value: "White", text: "White" },
  ],
  eyebrowTypeOptions: [
    { value: "Angry", text: "Angry" },
    { value: "AngryNatural", text: "Angry Natural" },
    { value: "Default", text: "Default" },
    { value: "DefaultNatural", text: "Default Natural" },
    { value: "FlatNatural", text: "Flat Natural" },
    { value: "RaisedExcited", text: "Raised Excited" },
    { value: "RaisedExcitedNatural", text: "Raised Excited Natural" },
    { value: "SadConcerned", text: "Sad Concerned" },
    { value: "SadConcernedNatural", text: "Sad Concerned Natural" },
    { value: "UnibrowNatural", text: "Unibrow Natural" },
    { value: "UpDown", text: "Up Down" },
    { value: "UpDownNatural", text: "Up Down Natural" },
  ],
  eyeTypeOptions: [
    { value: "Close", text: "Close" },
    { value: "Cry", text: "Cry" },
    { value: "Default", text: "Default" },
    { value: "Dizzy", text: "Dizzy" },
    { value: "EyeRoll", text: "Eye Roll" },
    { value: "Happy", text: "Happy" },
    { value: "Hearts", text: "Hearts" },
    { value: "Side", text: "Side" },
    { value: "Squint", text: "Squint" },
    { value: "Surprised", text: "Surprised" },
    { value: "Wink", text: "Wink" },
    { value: "WinkWacky", text: "Wink Wacky" },
  ],
  facialHairColorOptions: [
    { value: "Auburn", text: "Auburn" },
    { value: "Black", text: "Black" },
    { value: "Blonde", text: "Blonde" },
    { value: "BlondeGolden", text: "Blonde Golden" },
    { value: "Brown", text: "Brown" },
    { value: "BrownDark", text: "Brown Dark" },
    { value: "PastelPink", text: "Pastel Pink" },
    { value: "Platinum", text: "Platinum" },
    { value: "Red", text: "Red" },
    { value: "SilverGray", text: "Silver Gray" },
  ],
  facialHairTypeOptions: [
    { value: "Blank", text: "Blank" },
    { value: "BeardMedium", text: "Beard Medium" },
    { value: "BeardLight", text: "Beard Light" },
    { value: "BeardMajestic", text: "Beard Majestic" },
    { value: "MoustacheFancy", text: "Moustache Fancy" },
    { value: "MoustacheMagnum", text: "Moustache Magnum" },
  ],
  graphicTypeOptions: [
    { value: "Bat", text: "Bat" },
    { value: "Cumbia", text: "Cumbia" },
    { value: "Deer", text: "Deer" },
    { value: "Diamond", text: "Diamond" },
    { value: "Hola", text: "Hola" },
    { value: "Pizza", text: "Pizza" },
    { value: "Resist", text: "Resist" },
    { value: "Selena", text: "Selena" },
    { value: "Bear", text: "Bear" },
    { value: "SkullOutline", text: "Skull Outline" },
    { value: "Skull", text: "Skull" },
  ],
  hairColorOptions: [
    { value: "Auburn", text: "Auburn" },
    { value: "Black", text: "Black" },
    { value: "Blonde", text: "Blonde" },
    { value: "BlondeGolden", text: "Blonde Golden" },
    { value: "Brown", text: "Brown" },
    { value: "BrownDark", text: "Brown Dark" },
    { value: "PastelPink", text: "Pastel Pink" },
    { value: "Platinum", text: "Platinum" },
    { value: "Red", text: "Red" },
    { value: "SilverGray", text: "Silver Gray" },
  ],
  mouthTypeOptions: [
    { value: "Concerned", text: "Concerned" },
    { value: "Default", text: "Default" },
    { value: "Disbelief", text: "Disbelief" },
    { value: "Eating", text: "Eating" },
    { value: "Grimace", text: "Grimace" },
    { value: "Sad", text: "Sad" },
    { value: "ScreamOpen", text: "ScreamOpen" },
    { value: "Serious", text: "Serious" },
    { value: "Smile", text: "Smile" },
    { value: "Tongue", text: "Tongue" },
    { value: "Twinkle", text: "Twinkle" },
    { value: "Vomit", text: "Vomit" },
  ],
  skinColorOptions: [
    { value: "Tanned", text: "Tanned" },
    { value: "Yellow", text: "Yellow" },
    { value: "Pale", text: "Pale" },
    { value: "Light", text: "Light" },
    { value: "Brown", text: "Brown" },
    { value: "DarkBrown", text: "DarkBrown" },
    { value: "Black", text: "Black" },
  ],
  topTypeOptions: [
    { value: "NoHair", text: "No Hair" },
    { value: "Eyepatch", text: "Eyepatch" },
    { value: "Hat", text: "Hat" },
    { value: "Hijab", text: "Hijab" },
    { value: "Turban", text: "Turban" },
    { value: "WinterHat1", text: "Winter Hat 1" },
    { value: "WinterHat2", text: "Winter Hat 2" },
    { value: "WinterHat3", text: "Winter Hat 3" },
    { value: "WinterHat4", text: "Winter Hat 4" },
    { value: "LongHairBigHair", text: "Long Hair Big Hair" },
    { value: "LongHairBob", text: "Long Hair Bob" },
    { value: "LongHairBun", text: "Long Hair Bun" },
    { value: "LongHairCurly", text: "Long Hair Curly" },
    { value: "LongHairCurvy", text: "Long Hair Curvy" },
    { value: "LongHairDreads", text: "Long Hair  Dreads" },
    { value: "LongHairFrida", text: "Long Hair Frida" },
    { value: "LongHairFro", text: "Long Hair Fro" },
    { value: "LongHairFroBand", text: "Long Hair Fro Band" },
    { value: "LongHairNotTooLong", text: "Long Hair Not Too Long" },
    { value: "LongHairShavedSides", text: "Long Hair Shaved Sides" },
    { value: "LongHairMiaWallace", text: "Long Hair Mia Wallace" },
    { value: "LongHairStraight", text: "Long Hair Straight" },
    { value: "LongHairStraight2", text: "Long Hair Straight 2" },
    { value: "LongHairStraightStrand", text: "Long Hair Straight Strand" },
    { value: "ShortHairDreads01", text: "Short Hair Dreads 01" },
    { value: "ShortHairDreads02", text: "Short Hair Dreads 02" },
    { value: "ShortHairFrizzle", text: "Short Hair Frizzle" },
    { value: "ShortHairShaggyMullet", text: "Short Hair Shaggy Mullet" },
    { value: "ShortHairShortCurly", text: "Short Hair Short Curly" },
    { value: "ShortHairShortFlat", text: "Short Hair Short Flat" },
    { value: "ShortHairShortRound", text: "Short Hair Short Round" },
    { value: "ShortHairShortWaved", text: "Short Hair Short Waved" },
    { value: "ShortHairSides", text: "Short Hair Sides" },
    { value: "ShortHairTheCaesar", text: "Short Hair The Caesar" },
    { value: "ShortHairTheCaesarSidePart", text: "Short Hair The Caesar Side Part" },
  ],
  topColorOptions: [
    { value: "Black", text: "Black" },
    { value: "Blue01", text: "Blue 01" },
    { value: "Blue02", text: "Blue 02" },
    { value: "Blue03", text: "Blue 03" },
    { value: "Gray01", text: "Gray 01" },
    { value: "Gray02", text: "Gray 02" },
    { value: "Heather", text: "Heather" },
    { value: "PastelBlue", text: "Pastel Blue" },
    { value: "PastelGreen", text: "Pastel Green" },
    { value: "PastelOrange", text: "Pastel Orange" },
    { value: "PastelRed", text: "Pastel Red" },
    { value: "PastelYellow", text: "Pastel  Yellow" },
    { value: "Pink", text: "Pink" },
    { value: "Red", text: "Red" },
    { value: "White", text: "White" },
  ],
  defaultAvatar: {
    isCircle: true,
    circleColor: "#6fb8e0",
    topType: "NoHair",
    accessoriesType: "Blank",
    facialHairType: "Blank",
    clotheType: "ShirtCrewNeck",
    eyeType: "Default",
    eyebrowType: "Default",
    mouthType: "Default",
    skinColor: "Tanned",
    graphicType: "Bat",
    hairColor: "Black",
    facialHairColor: "Black",
    clotheColor: "Black",
    topColor: "Black",
  },
}

export default avatarOptions
