describe("Settings", () => {
  beforeEach(() => {
    cy.fixture("three-nodes.json").as("tapestry")
    cy.setup("@tapestry")
  })

  it(`should be able to save and edit an Avatar`, () => {
    // cy.request(Cypress.env("VUE_APP_AVATAR_POPUP"))
    // cy.getByTestId("user-settings-button").click()
    // cy.contains(/avatar/i).click()
    // cy.get(`[class="modal-body p-0"]`).as("scrollbar")
    // cy.get("@scrollbar").scrollTo("bottom")
    // cy.getByTestId("avatar-background-select").should("be.visible")
    // cy.getByTestId("avatar-background-select").select("Transparent")
    // cy.contains(/face/i).click()
    // cy.get("@scrollbar").scrollTo("bottom")
    // cy.getByTestId("avatar-eyebrow-select").should("be.visible")
    // cy.getByTestId("avatar-eyebrow-select").select("UpDown")
    // cy.contains(/hair/i).click()
    // cy.getByTestId("avatar-hair-select").should("be.visible")
    // cy.getByTestId("avatar-hair-select").select("LongHairBigHair")
    // cy.contains(/clothing/i).click()
    // cy.get("@scrollbar").scrollTo("bottom")
    // cy.getByTestId("avatar-glasses-select").should("be.visible")
    // cy.getByTestId("avatar-glasses-select").select("Wayfarers")
    // cy.contains(/save avatar/i).click()

    // cy.getByTestId("settings-button").click()
    // cy.contains(/avatar/i).click()
    // cy.get("@scrollbar").scrollTo("bottom")
    // cy.contains("Transparent").should("be.visible")
    // cy.contains(/face/i).click()
    // cy.get("@scrollbar").scrollTo("bottom")
    // cy.contains("UpDown").should("be.visible")
    // cy.contains(/hair/i).click()
    // cy.contains("LongHairBigHair").should("be.visible")
    // cy.contains(/clothing/i).click()
    // cy.get("@scrollbar").scrollTo("bottom")
    // cy.contains("Wayfarers").should("be.visible")
    // cy.contains(/Cancel/i).click()
  })
})
