# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress

on:
    push:
        branches: [master]
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - run: docker-compose pull
              working-directory: docker
            - name: Setup WP config
              working-directory: docker
              run: |
                cp wp-config-sample-nokey.php wp-config.php
                curl https://api.wordpress.org/secret-key/1.1/salt/ >> wp-config.php
            - name: Setup config.js 
              working-directory: templates/vue
              env: 
                LINK_KEY: ${{ secrets.LINK_PREVIEW_API_KEY }}
              run: echo 'export const LINK_PREVIEW_API_KEY = "'$LINK_KEY'"' > config.js
            - name: Setup cypress.json
              working-directory: templates/e2e
              run: cp cypress-gha.json cypress.json
            - uses: satackey/action-docker-layer-caching@v0.0.4
            - name: Launch containers
              run: docker-compose up -d
              working-directory: docker
            - name: Ping DB # Shouldn't be required but the next line doesn't succeed without this 
              run: docker exec wp bash -c "apt update; apt install iputils-ping -y; ping -c 5 db"
            - name: Install wordpress
              run: docker exec wp wp core install --allow-root --path=/var/www/html/ --url=localhost:8000 --admin_user=admin --admin_email=foo@bar.com --admin_password=secret --title=tapestry --debug
            - name: Install H5P
              run: docker exec wp wp plugin install h5p --allow-root
            - name: Activate plugins
              run: docker exec wp wp plugin activate tapestry-wp h5p --allow-root
            - name: Add GF CLI
              run: docker exec wp wp plugin install gravityformscli --activate --allow-root
            - name: Install Gravity Forms
              env: 
                GF_KEY: ${{ secrets.GRAVITY_FORMS_API_KEY }}
              run: docker exec wp wp gf install --key=$GF_KEY --allow-root
            - name: Ping DB # Shouldn't be required but the next line doesn't succeed without this 
              run: docker exec wp bash -c "apt update; apt install iputils-ping -y; ping -c 5 db"
            - name: Add Test Gravity Form
              run: docker exec wp wp gf form import /var/www/html/wp-content/plugins/tapestry-wp/templates/e2e/test-gf-form.csv --allow-root
            - name: Add users
              run: docker exec wp wp user create subscriber --allow-root sub@foo.com --role=subscriber --user_pass=subscriber
            - name: Set permalink structure
              run: docker exec wp wp rewrite structure %postname% --allow-root
            - name: Run tests
              run: docker exec e2e cypress run -b chrome --headless -s "cypress/integration/authoring/*"
              working-directory: docker
